# Generated by Django 3.2.12 on 2022-02-21 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20220221_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(default='category_1', on_delete=django.db.models.deletion.CASCADE, to='todo.category'),
        ),
    ]
